package rules;
dialect  "mvel"
import sample.Frame
import java.util.ArrayList
import java.util.Arrays;

declare QuestionResponse
    que: String
    res: String
end

rule "Which genere interests you?"
    when
    then
        QuestionResponse qr = new QuestionResponse();
        qr.setQue("Which genere interests you?");
        qr.setRes(Frame.optionDialog(
                qr.getQue(),
                "Supers",
                "Genere shouldn't matter",
                "Generes related to near present"));
        insert(qr);
end

rule "Based on real comics?"
    when
        exists QuestionResponse(que == "Which genere interests you?", res == "Supers")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Based on real comics?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "DC",
                        "Marvel",
                        "No or other"));
                insert(qr);
end

rule "Like undead?"
    when
        exists QuestionResponse(que == "Which genere interests you?", res == "Generes related to near present")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Like undead?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "I can be a vampire?!",
                        "If done well",
                        "Not really"));
                insert(qr);
end

rule "Humor, Spies, Gothic, Alternate Realities, or Cyberpunk?"
    when
        exists QuestionResponse(que == "Like undead?", res == "Not really")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Humor, Spies, Gothic, Alternate Realities, or Cyberpunk?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "Gothic",
                        "Alternate Realities",
                        "Cyberpunk",
                        "Humor",
                        "Spies"));
                insert(qr);
end

rule "Point pools for action resolution?"
    when
        exists QuestionResponse(que == "Humor, Spies, Gothic, Alternate Realities, or Cyberpunk?", res == "Alternate Realities")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Point pools for action resolution?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "Yes",
                        "No"));
                insert(qr);
end

rule "Really? (Genere)"
    when
        exists QuestionResponse(que == "Which genere interests you?", res == "Genere shouldn't matter")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Really?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "Yes",
                        "No, not really"));
                insert(qr);
end

rule "Which genere interests you? (loop avoiding)"
    when
        exists QuestionResponse(que == "Really?", res == "No, not really")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Which genere interests you?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "Supers",
                        "Generes related to near present"));
                insert(qr);
end

rule "What is du/dx = cu+xy?"
    when
        exists QuestionResponse(que == "Really?", res == "Yes")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("What is du/dx = cu+xy?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "A differential equation",
                        "It should be +x not +xy",
                        "Huh?"));
                insert(qr);
end

rule "Want some other generes mixed with that?"
    when
        exists QuestionResponse(que == "Humor, Spies, Gothic, Alternate Realities, or Cyberpunk?", res == "Cyberpunk")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Want some other generes mixed with that?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "Straight up",
                        "Some Magic",
                        "A little of everything"));
                insert(qr);
end

// ----- Final rules -----

rule "World of Darkness"
    when
        exists QuestionResponse(que == "Like undead?", res == "I can be a vampire?!")
    then
        Frame.answerDialog("World of Darkness");
end

rule "Call Of Cthulhu"
    when
        exists QuestionResponse(que == "Like undead?", res == "If done well")
    then
        Frame.answerDialog("Call Of Cthulhu");
end

rule "Paranoia"
    when
        exists QuestionResponse(que == "Humor, Spies, Gothic, Alternate Realities, or Cyberpunk?", res == "Humor")
    then
        Frame.answerDialog("Paranoia");
end

rule "Warhammer 40K RP"
    when
        exists QuestionResponse(que == "Humor, Spies, Gothic, Alternate Realities, or Cyberpunk?", res == "Gothic")
    then
        Frame.answerDialog("Warhammer 40K RP");
end

rule "Nobilis"
    when
        exists QuestionResponse(que == "Point pools for action resolution?", res == "Yes")
    then
        Frame.answerDialog("Nobilis");
end

rule "Amber"
    when
        exists QuestionResponse(que == "Point pools for action resolution?", res == "No")
    then
        Frame.answerDialog("Amber");
end

rule "HERO"
    when
        exists QuestionResponse(que == "What is du/dx = cu+xy?", res == "A differential equation")
    then
        Frame.answerDialog("HERO");
end

rule "GURPS"
    when
        exists QuestionResponse(que == "What is du/dx = cu+xy?", res == "It should be +x not +xy")
    then
        Frame.answerDialog("GURPS");
end

rule "CyberPunk 2020"
    when
        exists QuestionResponse(que == "Want some other generes mixed with that?", res == "Straight up")
    then
        Frame.answerDialog("CyberPunk 2020");
end

rule "Shadowrun"
    when
        exists QuestionResponse(que == "Want some other generes mixed with that?", res == "Some Magic")
    then
        Frame.answerDialog("Shadowrun");
end