package rules;
dialect  "mvel"
import sample.Frame
import java.util.ArrayList
import java.util.Arrays;

declare QuestionResponse
    que: String
    res: String
end

rule "Which genere interests you"
    when
    then
        QuestionResponse qr = new QuestionResponse();
        qr.setQue("Which genere interests you?");
        qr.setRes(Frame.optionDialog(
                qr.getQue(),
                "Supers",
                "Genere shouldn't matter",
                "Generes related to near present"));
        insert(qr);
end

rule "Based on real comics"
    when
        exists QuestionResponse(que == "Which genere interests you?", res == "Supers")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Based on real comics?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "DC",
                        "Marvel",
                        "No or other"));
                insert(qr);
end

rule "Like undead"
    when
        exists QuestionResponse(que == "Which genere interests you?", res == "Generes related to near present")
    then
        QuestionResponse qr = new QuestionResponse();
                qr.setQue("Like undead?");
                qr.setRes(Frame.optionDialog(
                        qr.getQue(),
                        "I can be a vampire?!",
                        "If done well",
                        "No really"));
                insert(qr);
end

rule "Final"
    when
        exists QuestionResponse(que == "Like undead?", res == "I can be a vampire?!")
    then
        Frame.answerDialog("World of Darkness!");
end
